# first base image is node to build the app
FROM node:21.1.0-alpine as builder

USER node

RUN mkdir -p /home/node/app
WORKDIR '/home/node/app'

COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

RUN npm run build


#second base image is the nginx build

FROM nginx:1.25.3-alpine as runner
COPY --from=builder /home/node/app/build  /usr/share/nginx/html
